### PR TITLE
Fix pk pkcs11 memleak

### PR DESCRIPTION
**Pull request by paulbartell**
Remove unused iot_crypto.c file.
Fix memory leak in mbedtls_pkcs11 transport implementation

### CODE REVIEW

**Comment by KazukiMochizuki926** [comment]
@paulbartell - san,
Thank you for fixing the memory leak.
However, iot_crypto.c and iot_crypto.h are used by OTA PAL.
We plan to download the source code and check the details.

**Comment by paulbartell** [comment]
I see. I dropped the commit removing iot_crypto.c.

The ota_pal.c looks very complex (with a queue and task to perform flashing). Is this level of complexity necessary?

**Comment by HirokiIshiguro** [comment]
Hi, Paul-san, thank you for the comment for ota_pal. Yes this level of complexity is necessary. RX MCU internal FLASH system has Back Ground Operation(BGO) mode that can support flashing during OTA data receiving or other system behavior. Of course we would like to keep re-factor for keeping the code more simpler.

**Comment by KazukiMochizuki926** [comment]
@HirokiIshiguro - san,
Thank you for your comment.
@paulbartell - san,
We also confirmed that no memory leak occurred after TLS connection/disconnection.
The removed lPKCS11PkMbedtlsCloseSessionAndFree function was used in the Fleet Provisioning Demo, so we'll fix it.

**Pull request merged**
